/* eslint-disable @next/next/no-img-element */
import { Analysis } from "@/lib/types";

/** AI analyst note with the personal advisor branding. */
export default function AdvisorCard({ a, base }: { a: Analysis; base: string }) {
  return (
    <div>
      <div className="flex items-center gap-3 mb-3">
        <img
          src="/advisor.jpg"
          alt="Abhinay Jandrajupalli"
          className="h-11 w-11 rounded-full object-cover border border-gold/50 gold-ring"
        />
        <div>
          <div className="text-sm font-semibold text-slate-100">
            Abhinay <span className="gold-text">·</span> Sam Market Desk
          </div>
          <div className="text-[11px] text-dim font-mono">
            {"Generated by the quant engine from live market data"}
          </div>
        </div>
        <span className="ml-auto rounded-full border border-gold/40 bg-gold/10 px-2.5 py-0.5 text-[10px] font-mono text-gold">
          {base}/USDT · daily
        </span>
      </div>
      <p className="text-sm leading-relaxed text-muted whitespace-pre-line">{a.aiSummary}</p>
      <p className="text-[10px] text-dim mt-3">Educational analysis, not financial advice.</p>
    </div>
  );
}
